import {chromium} from '@playwright/test';import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {example} from '../src/profile.mjs';
await fs.mkdir('test-results/browser',{recursive:true});
const server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'pipe'});
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(new Error(`Server exited ${code}`)));});
let browser;const report={status:'running',browserSandbox:true,checks:[],screenshots:[],pageErrors:[]};
try{
 browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await context.newPage();
 const foreign=[];page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173'))foreign.push(r.url());});
 await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.repair-count strong');
 const count=async n=>assert.equal(await page.locator('.repair-count strong').textContent(),String(n));
 const solve=()=>page.locator('#solve').click();
 const download=async name=>{const pending=page.waitForEvent('download');await page.locator('#download').click();const dl=await pending;assert.equal(dl.suggestedFilename(),'PinMendDemo.zip');await dl.saveAs(`test-results/browser/${name}.zip`);};
 await count(4);assert.ok(await page.locator('#download').isDisabled());await page.locator('#ack').check();await download('both-repaired');report.checks.push('Japanese default, min4, required frequency acceptance, real ZIP download');
 await page.screenshot({path:'test-results/browser/desktop-ja.png',fullPage:true});report.screenshots.push('desktop-ja.png');
 await page.locator('#language').click();assert.equal(await page.locator('html').getAttribute('lang'),'en');await count(4);assert.ok(await page.locator('#download').isEnabled());report.checks.push('Language switch preserves mapping and acknowledgement');
 await page.screenshot({path:'test-results/browser/desktop-en.png',fullPage:true});report.screenshots.push('desktop-en.png');
 await page.locator('#servo').uncheck();assert.ok(await page.locator('#export-area').isHidden());await page.locator('#tone').uncheck();await solve();await count(0);await download('no-features-original');report.checks.push('No-feature min0 and stale result invalidation');
 await page.locator('#servo').check();await solve();await count(2);await download('servo-only-repaired');report.checks.push('Servo-only min2, 490 Hz preserved');
 await page.locator('#reset').click();await page.getByRole('checkbox',{name:'Keep pin fixed BUTTON_A',exact:true}).check();await solve();assert.equal(await page.locator('#status').textContent(),'No valid mapping');assert.match(await page.locator('#output').textContent(),/2\/1/);assert.ok(await page.locator('#export-area').isHidden());report.checks.push('Fixed D5 infeasible demand2 capacity1 with no export');
 await page.screenshot({path:'test-results/browser/infeasible-en.png',fullPage:true});report.screenshots.push('infeasible-en.png');
 await page.locator('#reset').click();await page.getByRole('checkbox',{name:'Unavailable pins D6',exact:true}).check();await solve();assert.equal(await page.locator('#status').textContent(),'No valid mapping');report.checks.push('Unavailable pin constraint');
 await page.locator('#reset').click();await page.locator('#add').click();assert.equal(await page.locator('.signal-row').count(),7);await page.getByRole('button',{name:'Remove SIGNAL_1',exact:true}).click();assert.equal(await page.locator('.signal-row').count(),6);await solve();await count(4);report.checks.push('Add/delete/repeated solve');
 await page.locator('#import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(example()))});await count(4);report.checks.push('Valid JSON import');
 const aliases=['A0','A1','A2','A3','A4','A5','A6','A7','SPI_SS','SPI_MOSI','WIRE_SDA','WIRE_SCL'];
 const custom={schema:'pinmend/1',features:{servo:false,tone:false},unavailable:[],signals:aliases.map((id,i)=>({id,type:'digital-out',pin:i+2,fixed:false}))};
 await page.locator('#import').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(custom))});await count(0);await download('custom-aliases');report.checks.push('Custom pin/identifier JSON exported as actual source ZIP');
 await page.locator('#reset').click();
 await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});assert.match(await page.locator('#error').textContent(),/Could not import/);await count(4);report.checks.push('Malformed import preserves current project');
 const evil=example();evil.signals[0].id='<img src=x onerror=alert(1)>';await page.locator('#import').setInputFiles({name:'evil.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(evil))});assert.match(await page.locator('#error').textContent(),/Signal IDs/);assert.equal(await page.locator('#signals img').count(),0);report.checks.push('Hostile identifier rejected');
 await page.locator('#import').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(65536,32)});assert.match(await page.locator('#error').textContent(),/64 KiB/);report.checks.push('Bounded JSON import');
 await page.evaluate(()=>{const original=File.prototype.text;File.prototype.text=function(){if(this.name==='slow.json')return new Promise(resolve=>{window.releasePinmendImport=()=>original.call(this).then(resolve);});return original.call(this);};});
 await page.locator('#import').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(example({servo:false,tone:false})))});await page.locator('#reset').click();await page.evaluate(()=>window.releasePinmendImport());await count(4);
 await page.locator('#import').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(example()))});await page.locator('#import').setInputFiles({name:'fast.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(example({servo:false,tone:false})))});await count(0);await page.evaluate(()=>window.releasePinmendImport());await count(0);report.checks.push('Delayed older imports cannot overwrite reset or newer import');
 await page.locator('#reset').click();await page.keyboard.press('Control+Home');await page.locator('body').click({position:{x:1,y:1}});await page.keyboard.press('Tab');assert.ok(await page.locator('.skip').evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'workspace');report.checks.push('Keyboard skip link');
 await page.locator('#tone').focus();await page.keyboard.press('Space');assert.ok(!(await page.locator('#tone').isChecked()));await page.locator('#solve').focus();await page.keyboard.press('Enter');await count(2);report.checks.push('Keyboard toggle and solve');
 await page.locator('#reset').click();await page.locator('#language').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/browser/mobile-ja.png',fullPage:true});report.screenshots.push('mobile-ja.png');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('#language').click();await page.screenshot({path:'test-results/browser/mobile-en.png',fullPage:true});report.screenshots.push('mobile-en.png');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.setViewportSize({width:320,height:760});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push('Responsive 390px JA/EN and 320px no horizontal overflow');
 const pending=page.waitForEvent('filechooser');await page.locator('#import-button').focus();await page.keyboard.press('Enter');await pending;report.checks.push('Keyboard import control');
 assert.deepEqual(foreign,[]);assert.deepEqual(report.pageErrors,[]);report.checks.push('No external requests, no JavaScript errors');
 report.status='passed';console.log(JSON.stringify(report,null,2));
}catch(e){report.status='failed';report.error=e.stack;throw e;}finally{await fs.writeFile('test-results/browser/report.json',JSON.stringify(report,null,2)+'\n');if(browser)await browser.close();server.kill();}
